seek-oss/serverless-haskell

- serverless-plugin/index.js
No Node dependencies are present in the uploaded files anyway, and calculating
which ones are for development only takes time.
> Disable excluding Node dependencies

- serverless-plugin/index.js
I had `--nix` set in my user config file. It doesn't play well with `--docker` and causes the script to fail in fairly inscrutable ways. I'm fairly confident that it's correct to always turn off `nix` when turning on `docker` because calling `stack` with both produces error messages like:
```
Executable named nix-shell not found on path: [/opt/host/bin,/home/.../code/serverless-test/.stack-work/docker/_home/.local/bin,/root/.cabal/bin,/root/.local/bin,/opt/ghc/8.2.2/bin,/usr/local/sbin,/usr/local/bin,/usr/sbin,/usr/bin,/sbin,/bin]
```
which is very wrong for NixOS.
> Disable nix when enabling docker

- README.md
- example-project/package.json
- integration-test/expected/local_output.txt
- integration-test/expected/offline_output.txt
- integration-test/run.sh
- integration-test/skeleton/ApiGateway.hs
- integration-test/skeleton/package.yaml
- integration-test/skeleton/serverless.yml
- serverless-plugin/index.js
- serverless-plugin/package-lock.json
- serverless-plugin/package.json
- src/AWSLambda.hs
- src/AWSLambda/Events/APIGateway.hs
- src/AWSLambda/Handler.hs
Turns out that using the same handlers as we're already uploading to AWS works perfectly for `sls invoke local` and `sls offline start` ([serverless-offline](https://github.com/dherault/serverless-offline/)). Just needed to remove the check on the AWS environment variable.
Fixes #32.
Fixes #48.
Currently blocked on https://github.com/dherault/serverless-offline/issues/436 (serverless-offline part, `invoke local` works).
> Support serverless-offline and invoke local

- serverless-plugin/index.js
This supersedes https://github.com/seek-oss/serverless-haskell/pull/60, adding support for multiple installed package versions, and finding the right one, by using `stack ls dependencies` instead of `ghc-pkg`.
The check now happens before `stack build`, because we know it immediately, instead of after it has been built, like with `ghc-pkg`.
Note: Sorry for the multiple PRs, but it was way easier (for me) than rebasing on the different branch :)
> Handle matching against multiple stack versions, supersedes #60

- serverless-plugin/package-lock.json
- serverless-plugin/package.json
- No longer depends on a vulnerable https-proxy-agent
- Works with Node 10.7
> Update serverless dependency

- src/AWSLambda/Events/APIGateway.hs
- test/AWSLambda/Events/APIGatewaySpec.hs
This allows access to the authorizer propery on the api gateway lambda request context.  The authorizier propery is used during cognito user pools where authorizer.claims contains the claims from the token.  The authorizer is also used with lambda authorizers where the return value from the lambda authorizer claims is put directly on the authorizer property.
Documentation is here: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
> Add authorizer parsing to proxy lambda request context

- README.md
- example-project/serverless.yml
- integration-test/expected/local_output_js.txt
- integration-test/expected/output_js.json
- integration-test/run.sh
- integration-test/skeleton/jsfunc/handler.js
- integration-test/skeleton/serverless.yml
- integration-test/tests.sh
- serverless-plugin/index.js
- src/AWSLambda.hs
Currently, if the plugin is enabled, all the functions will be built as Haskell, and there is no way to deploy Haskell and other functions together. In vanilla Serverless, it is possible to deploy multiple functions with different runtimes by specifying the `runtime` key in the individual function definitions.
This change makes the plugin use the `runtime` option in the service or individual function definitions to distinguish Haskell functions, and only build with Stack ones where `runtime` is `haskell`.
Before passing control to the main Serverless code, the plugin sets `runtime` to `nodejs8.10` so the functions are deployed properly. Currently the user must set that which is an embarrassing implementation detail.
Fixes #65.
This is a breaking change and will require a version bump.
> Use "runtime" option to distinguish Haskell functions

- travis/deploy
The fix for https://github.com/commercialhaskell/stack/issues/3739 was finally released in 1.9.1, workaround no longer needed.
> Remove workaround for Stack <1.9 trying to sign package

- src/AWSLambda/Events/APIGateway.hs
- test/AWSLambda/Events/APIGatewaySpec.hs
With more testing against lambda and api gateway authorizers, it is weird because sometimes for routes with no auth, api gateway doesn't send the authorizer field at all in the request context but sometimes it sends an empty object with no claims.  I couldn't figure out when an empty object is sent and when the field is just missing.
In any case, the fix is to just make the authorizer field optional in the request context.  Just in case I also made the prinicpalId field optional so the parsing doesn't fail if it is missing.
> API Gateway: authorizer in the request context is not always present

- .gitignore
- ChangeLog.md
- README.md
- integration-test/run.sh
- package.yaml
- serverless-plugin/.eslintrc
- serverless-plugin/handler.template.js
- serverless-plugin/index.js
- src/AWSLambda/Handler.hs
* Change the communication method between the JavaScript wrapper and the Haskell
process to TCP. This fixes errors like "Resource vanished: broken pipe" when
running the Haskell executable standalone.
* Do not crash when `ldd` is not found when locally invoking a function on macOS.
* Fix error message about no Haskell functions being found when invoking a
function locally.
> Fix regressions in 0.8.3

- integration-test/run.sh
- integration-test/skeleton/serverless.yml
- integration-test/tests.sh
- serverless-plugin/index.js
Serverless [supports variables](https://serverless.com/framework/docs/providers/aws/guide/variables/) in the configuration file.
However, they are not expanded in the plugin _constructor_ yet (https://forum.serverless.com/t/serverless-plugin-resolving-variable-references/2233/2), so specifying `docker: false` via a _variable_ does not turn off Docker.
This PR fixes the expanding by only checking the value of `docker` _after_ the constructor.
See `fix-variables-test` for a failing test.
> Fix expanding variables in custom section

- .travis.yml
Builds for LTS 13 failed to upload the cache previously, leading to each commit taking upwards of 30 minutes to build there. Allow more time for caching so that future builds are fast.
> Allow more time for caching on Travis CI

- example-project/package.json
- integration-test/run.sh
- integration-test/tests.sh
Due to https://github.com/serverless/serverless/issues/6034, `sls package` cannot be run without AWS credentials.
> Move sls package test out of dry run section

- serverless-plugin/index.js
- src/AWSLambda.hs
`stack build <component>` has to reconfigure _something_ (Cabal?) each time, which makes for slower rebuilds. Make `stack build` the default, with an option to revert to building individual executables instead.
> Build the whole project with Stack by default

- integration-test/run.sh
- integration-test/skeleton/stack.yaml
- integration-test/skeleton/subdir/stack.yaml
In Stack 2, this syntax is no longer valid:
```
packages:
- .
- location: somewhere
extra-dep: true
```
> Stack 2 compatibility

- ChangeLog.md
- package.yaml
- serverless-haskell.hsfiles
- serverless-plugin/package-lock.json
- serverless-plugin/package.json
- src/AWSLambda/Events/S3Event.hs
- src/AWSLambda/Orphans.hs
Small PR. It's a breaking change but not one that should be hard to fix. `ObjectVersionId` is a newtype that is used in `amazonka-s3` for referring to S3 object versions. We already use `BucketName` and `ObjectKey` from `amazonka-s3` so it makes sense to use `ObjectVersionId` too for consistency.
> Use ObjectVersionId newtype

- .travis.yml
- ChangeLog.md
- stack.yaml.lock
- travis/before_install
0.9.2 wasn't released because the changes to `.travis.yml` meant the deployment stage was never run (it relied on a specific build job which was merged into another).
This PR separates [build and deployment stages in CI](https://docs.travis-ci.com/user/build-stages/) and ensures the deployment stage is run after _all_ build jobs are successful.
Because the deployment stage is no longer attached to any single build job, further changes to the build jobs (e.g. adding or removing LTS) will not affect the deployment process.
> Separate deployment stage

- serverless-plugin/config.js
AWS Lambda supports Node 12 now.
> Update Node runtime to 12.x

- ChangeLog.md
- serverless-plugin/ld.js
- travis/before_install
I've updated NodeJS on Travis to 12, but it should still work on 10 too.
> Don't parse all objdump output when checking glibc version

- integration-test/run.sh
- integration-test/tests.sh
- serverless-plugin/package-lock.json
- serverless-plugin/package.json
* More guards for shell (mis)behavior. I'd like to rewrite the integration test in a not-hostile language...
* Retry downloading `snapshots.json` from Stackage because it keeps timing out.
* Update JS packages.
> Fix integration test failures

- .gitignore
- ChangeLog.md
- integration-test/run.sh
- serverless-plugin/package.json
- travis/deploy
0.10.3 failed to publish because TypeScript wasn't compiled: https://travis-ci.org/github/seek-oss/serverless-haskell/jobs/676844329#L626
> Fix npm packaging

- .github/workflows/deploy.yaml
- ChangeLog.md
- stack.yaml
We've used a new feature of Stack 2.3.1 - using `HACKAGE_USERNAME` and `HACKAGE_PASSWORD` environment variables - but it's [buggy](https://github.com/commercialhaskell/stack/issues/5290).
> Fix deployment

- src/AWSLambda/Events.hs
- src/AWSLambda/Events/Records.hs
- src/AWSLambda/Events/SNSEvent.hs
- src/AWSLambda/Events/SQSEvent.hs
These specialised main functions make working with SQS, SNS and S3 events much simpler. This probably deserves some examples in the README (which currently doesn't mention these event types), but I'll do that separately.
> Add specialised main functions for event types

- ChangeLog.md
- package.yaml
- src/AWSLambda/Events.hs
- src/AWSLambda/Events/SNSEvent.hs
- test/AWSLambda/Events/SQSEventSpec.hs
Turns out there was a bug in the traversal of SNS messages contained within an SQS event. Each record in the SQS event contains only one SNS messages, not a sequence of message records. I've fixed this and added a test.
> Fix for SNS messages embedded in SQS

- bumpversion
- serverless-haskell.hsfiles
This is supposed to be updated by `bumpversion`, but has somehow got out of sync.
> Update version in hsfiles

- integration-test/run.sh
- integration-test/tests.sh
Due to race conditions between the function result and its output, the
integration tests can fail. Check individual lines in the output instead
of the complete text.
> Integration tests: check expected output line by line

- .github/workflows/main.yaml
- README.md
- bumpversion
- serverless-haskell.hsfiles
- stack.yaml
- stack.yaml.lock
- update-lts
Updates resolver in `serverless-haskell.hsfiles` to latest LTS (16.3) and modifies `bumpversion` to keep this up-to-date.
> Update resolver in hsfiles

- integration-test/skeleton/serverless.yml
Remove deprecation warning about the new hashing version from integration test output
> Use new lambdaHashingVersion

- README.md
Added a bit of clarification so that people don't get turned off by reading this top google search result right away: https://www.haskelltutorials.com/haskell-aws-lambda/avoid-serverless-haskell.html
> Update readme for clarification
