seek-oss/serverless-haskell

- package.yaml
- test/AWSLambda/Events/KinesisEventSpec.hs
- test/AWSLambda/Events/S3EventSpec.hs
- test/AWSLambda/Events/SNSEventSpec.hs
aeson-qq is not on Stackage, use raw-strings-qq instead
> Prepare for Stackage: use raw-strings-qq for quasiquotation

- .travis.yml
- serverless-plugin/.eslintrc
- serverless-plugin/handler.template.js
- serverless-plugin/package-lock.json
- serverless-plugin/package.json
Add JS syntax check to the tests as well.
Fixes #13.
> Fix JS strict mode syntax

- serverless-plugin/index.js
> Check that the Haskell package version corresponds to the JS one

- README.md
- example-project/serverless.yml
- integration-test/run.sh
- integration-test/serverless.yml
- serverless-plugin/package-lock.json
- serverless-plugin/package.json
- src/AWSLambda.hs
* Update JS dependencies versions
* Update recommended Node runtime to 8
* Use LTS 10 in the integration test (work around #34)
> Update dependencies versions and fix integration test

- package.yaml
- src/AWSLambda/Events/APIGateway.hs
- src/AWSLambda/Orphans.hs
- stack.yaml
- test/AWSLambda/Events/APIGatewaySpec.hs
Fixes https://github.com/seek-oss/serverless-haskell/issues/37.
> Http types

- serverless-plugin/index.js
Fixes #38. Currently blocked by https://github.com/commercialhaskell/stack/issues/4041.
> Remove deprecated stack list-dependencies

- README.md
- serverless-plugin/index.js
- src/AWSLambda.hs
> Default to building with Docker

- serverless-plugin/index.js
- src/AWSLambda.hs
> Support (but discourage) static executables

- README.md
- serverless-plugin/index.js
- src/AWSLambda.hs
> More documentation about ensuring the NPM and Stack package versions match

- .travis.yml
- ChangeLog.md
- serverless-plugin/index.js
- travis/install
* Warn if no Haskell functions found, as upgrading from 0.7 can trip people up.
* Better wording for package version mismatches.
> Check for Haskell functions

- bumpversion
- travis/before_install
- travis/install
* Install NPM for releasing
* Fix changelog updating
> Fix releasing again

- serverless-plugin/package-lock.json
- serverless-plugin/package.json
NPM reported vulnerable transitive dependencies; apply recommended fixes
> Update NPM packages

- example-project/package.json
- integration-test/run.sh
- serverless-haskell.hsfiles
- serverless-plugin/package-lock.json
- serverless-plugin/package.json
https://github.com/serverless/serverless/issues/6034 is fixed, bump version and move the test back.
> Revert disabling "sls package" for dry run

- serverless-plugin/index.js
Verified that the wet tests pass.
> Update AWS runtime to Node 10.x

- serverless-plugin/handler.template.js
> Close listening socket after establishing connection

- ChangeLog.md
- deploy
* Don't write config for Stack upload, rely on environment variables.
Fixes the issue where the directory for the config file didn't exist
* Test uploading to both Hackage and NPM before uploading to either
> Fix deployment

- README.md
- latest-lts
- src/AWSLambda.hs
I went through the manual instructions from scratch and added some missing / incorrect info. Fixes #143.
> Improved manual instructions

- ChangeLog.md
- index.ts
- integration-test/skeleton/serverless.yml
- package-lock.json
- package.json
- tsconfig.json
> Add Serverless validation schema

- integration-test/skeleton/serverless.yml
https://github.com/seek-oss/serverless-haskell/runs/1393466951?check_suite_focus=true#step:10:313
> Opt in to new API Gateway naming

- ChangeLog.md
- package.yaml
- src/AWSLambda/Events/APIGateway.hs
- test/Data/Aeson/TestUtil.hs
See https://github.com/commercialhaskell/stackage/issues/5878.
> Don't rely on key ordering in JSON tests
